theme: jekyll-theme-minimal

title: [WELCOME]
description: [I am Kauane Maiara Bordin and this is my website! I am a Brazilian scientist interested in Community and Functional Ecology.]
email: [kauanembordin@gmail.com]
 social_links:
    twitter: kmbordin
    github:  kmbordin
    # instagram: jekyll
    
    # If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
- about.md

