theme: jekyll-theme-minimal

title: [WELCOME]
description: [I am Kauane Maiara Bordin and this is my website! I am a Brazilian scientist interested in Community, Functional and Forest Ecology.]
email: [kauanembordin@gmail.com]

twitter_username: kmbordin

