theme: jekyll-theme-minimal

title: [WELCOME]
description: [I am Kauane Maiara Bordin and this is my website! I am a Brazilian scientist interested in Community and Functional Ecology.]
email: [kauanembordin@gmail.com]
 social_links:
    twitter: kmbordin
    github:  kmbordin
    # instagram: jekyll

